<?php
/*
 * Creates the SVG thermometer
 */

function donation_thermometer_strlen( $value ) {
    return function_exists( 'mb_strlen' ) ? mb_strlen( $value ) : strlen( $value );
}

// Returns array( float[] values, bool trailing 'off' flag ).
function therm_parse_list( $raw, $decsep ) {
    $items = array_slice( explode( ';', sanitize_text_field( $raw ) ), 0, 50 );
    $off   = ( end( $items ) == 'off' );
    if ( $off ) {
        array_splice( $items, -1 );
    }

    foreach ( $items as &$item ) {
        if ( $decsep === ',' ) {
            $item = floatval( str_replace( ',', '.', str_replace( '.', '', strval( $item ) ) ) );
        } else {
            $item = floatval( str_replace( ',', '', strval( $item ) ) );
        }
    }
    unset( $item );

    return array( $items, $off );
}

function donation_thermometer_normalize_align( $align ) {
    $align = strtolower( trim( (string) $align ) );

    // Current canonical values.
    if ( in_array( $align, array( 'left', 'center', 'right' ), true ) ) {
        return $align;
    }

    // Legacy values generated by older plugin versions.
    $legacy_alignments = array(
        'display:block; float:left;'                    => 'left',
        'display:block;float:left;'                     => 'left',
        'display:block; float:right;'                   => 'right',
        'display:block;float:right;'                    => 'right',
        'display:block; margin-left:auto; margin-right:auto;' => 'center',
        'display:block;margin-left:auto;margin-right:auto;'   => 'center',
        'centre' => 'center',
    );

    return $legacy_alignments[ $align ] ?? 'left';
}

function therm_sanitize_dimension( $value ) {
    $value = trim( (string) $value );

    // Permit numbers, px, and percentages only.
    if ( preg_match( '/^\d+(?:\.\d+)?(?:px|%)?$/', $value ) ) {
        return $value;
    }

    return '';
}

function thermhtml($thermProperties){
    ob_start();
    $thermDefaultStyle = get_donation_thermometer_style_defaults();
    $optionsCSS = wp_parse_args( get_option('thermometer_style',$thermDefaultStyle), $thermDefaultStyle);
    $decsep      = sanitize_text_field($thermProperties['decsep']);
    $sep         = ($thermProperties['sep'] === ' ') ? ' ' : sanitize_text_field($thermProperties['sep']);
    $orientation = (sanitize_key($thermProperties['orientation']) === 'landscape') ? 'landscape' : 'portrait';
    $width_tp    = therm_sanitize_dimension($thermProperties['width'] ?? '');
    $height_tp   = therm_sanitize_dimension($thermProperties['height'] ?? '');
    $trailing    = ($thermProperties['trailing'] === 'true') ? 'true' : 'false';
    $shadow      = (int) $thermProperties['shadow'];
    $swap_requested = (int) $thermProperties['swapValues'];

    // thermometer values and units
    list( $raisedA, $raisedOff ) = therm_parse_list( $thermProperties['raised'], $decsep );
    $showRaised  = $raisedOff ? 0 : (int) $thermProperties['showRaised'];
    $raisedTotal = array_sum($raisedA);
    $swap = ( $swap_requested === 1 && $raisedTotal > 0 ) ? 1 : 0;

    list( $targetA, $targetOff ) = therm_parse_list( $thermProperties['target'], $decsep );
    $showTarget = $targetOff ? 0 : (int) $thermProperties['showTarget'];

    $showSubTargets = (int) $thermProperties['targetlabels'];
    $targetTotal    = max(0.01, (float) end($targetA));
    $currency = sanitize_text_field($thermProperties['currency']);
    $decimals = min(10, absint($thermProperties['decimals']));
    $formatValue = static function ( $n ) use ( $decimals, $decsep, $sep, $currency, $trailing ) {
        $formatted = number_format( $n, $decimals, $decsep, $sep );
        return ( $trailing === 'true' ) ? $formatted . $currency : $currency . $formatted;
    };
    $raisedPercent = number_format(($raisedTotal/$targetTotal * 100),$decimals,$decsep,$sep);
    $raisedValue = $formatValue($raisedTotal);
    $targetValue = $formatValue($targetTotal);
    $tValue = ($swap == 1) ? $raisedValue : $targetValue;

    if ($showSubTargets === 1 && count($targetA) > 1) {
        $subTargetValue  = $formatValue($targetA[count($targetA) - 2]);
    } else {
        $subTargetValue  = '0';
    }

    // colours & legend
    $colorListA = (count($raisedA) > 1 && !empty($thermProperties['colorList'])) ? explode(';', rtrim(sanitize_text_field($thermProperties['colorList']), ';')) : array($thermProperties['fill']);
    foreach ( $colorListA as &$color ) {
        $color = sanitize_hex_color( trim( $color ?? '' ) ) ?: '#000000';
    }
    unset( $color );
    $fill2 = sanitize_hex_color( $thermProperties['fill2'] ?? '' ) ?: '#fdae61';

    $svg_id_prefix = 'therm_' . wp_unique_id();
    $gradID = $svg_id_prefix . '_gradient_' . md5($colorListA[0] . '_' . $fill2);
    if ($orientation === 'landscape') {
        $gradient = '<linearGradient id="' . $gradID . '" x1="0" x2="1" y1="0" y2="0"><stop style="stop-color: ' . esc_attr($colorListA[0]) . '" offset="0%" /><stop style="stop-color: ' . esc_attr($fill2) . '" offset="100%" /></linearGradient>';
    } else {
        $gradient = '<linearGradient id="' . $gradID . '" x1="0" x2="0" y1="0" y2="1"><stop style="stop-color: ' . esc_attr($fill2) . '" offset="0%" /><stop style="stop-color: ' . esc_attr($colorListA[0]) . '" offset="100%" /></linearGradient>';
    }

    $legend = rtrim(sanitize_text_field($thermProperties['legend']),';'); // trim last semicolon if added
    $legendA = array_slice(explode(';', $legend), 0, count($raisedA));

    $percentageColor = sanitize_hex_color( $thermProperties['percentageColor'] ?? '' ) ?: '#000000';
    $targetColor = sanitize_hex_color( $thermProperties['targetColor'] ?? '' ) ?: '#000000';
    $raisedColor = sanitize_hex_color( $thermProperties['raisedColor'] ?? '' ) ?: '#000000';
    $subTargetColor = sanitize_hex_color( $thermProperties['subtargetColor'] ?? '' ) ?: '#8a8a8a';
    $shadowID = $svg_id_prefix . '_shadow';
    $basicShadow = ($shadow == 1) ? 'url(#' . $shadowID . ')' : '';

    // basic properties of the thermometer
    $minH = ($orientation == 'landscape') ? 59.5 : 246;
    $maxH = ($orientation == 'landscape') ? 269.5 : 36;
    $tickStep = 42;
    $leftM = ($orientation == 'landscape') ? 23.5 : 20; // Y : X
    $rightM = ($orientation == 'landscape') ? 59.5 : 56; // Y : X
    $tickM = in_array(sanitize_key($thermProperties['ticks']), array('left', 'top'), true) ? $leftM : $rightM;
    $markerSize = 5;
    $legendStep = 15;
    $transformY  = ($orientation === 'landscape') ? 0 : (($showTarget === 1) ? 0 : 18);
    $viewboxY    = ($showTarget === 1) ? 305 : 287;
    $viewboxX2   = ($orientation === 'landscape') ? 90 : 76;

    $targetAnchorPoint = $maxH;
    $targetAnchor      = 'middle';
    if ($orientation === 'landscape') {
        if (donation_thermometer_strlen($targetValue) >= 8) {
            $targetAnchorPoint = $viewboxY - 10;
            $targetAnchor      = 'end';
        }
    }

    $targetLen = donation_thermometer_strlen($tValue);
    if ($tickM === $rightM){	// left or right ticks
        $viewboxX1 = -4; // landscape; portrait is set below
        $majorTickL = $rightM - 13;
        $minorTickL = $rightM - 6;
        $markerMargin = $rightM + 2;
        $subMarkerMargin = ($orientation == 'landscape') ? $leftM - 2 : $rightM + 2;
        $raisedMargin = ($orientation == 'landscape') ? $rightM + 15 : $rightM + 10;
        $subTargetMargin = ($orientation == 'landscape') ? $leftM - 15 : $rightM + 10;
        $raisedAnchor = 'start';
    }
    else{
        $viewboxX1 = 0; // landscape; portrait is set below

        $majorTickL = $leftM + 13;
        $minorTickL = $leftM + 6;
        $markerMargin = $leftM - 2;
        $subMarkerMargin = ($orientation == 'landscape') ? $rightM + 2 : $leftM - 2;
        $raisedMargin = ($orientation == 'landscape') ? $leftM - 15 : $leftM - 10;
        $subTargetMargin = ($orientation == 'landscape') ? $rightM + 15 : $leftM - 10;
        $raisedAnchor = 'end';
    }

    if($orientation != 'landscape'){
        // Raised/sub-target labels sit on the tick side; the box is centred on the thermometer (x=38) and offset towards the labels.
        $raisedLabelLen = ($showRaised === 1) ? donation_thermometer_strlen(($swap == 1) ? $targetValue : $raisedValue) : 0;
        $subLabelLen    = ($showSubTargets === 1 && count($targetA) > 1) ? donation_thermometer_strlen($subTargetValue) : 0;
        $sideLen = max($raisedLabelLen, $subLabelLen);
        $labelLeft  = ($tickM === $leftM) ? -7 * $sideLen : 0;
        $labelRight = ($tickM === $rightM) ? 76 + 8 * $sideLen : 76;
        $shift = (($tickM === $rightM) ? 1 : -1) * $raisedLabelLen * 1.375;

        // Target label is centred on x=38 (16px default font, ~9.5 units/char).
        $targetHalf = ($showTarget === 1) ? $targetLen * 4.75 + 4 : 0;
        $half = max(38 + $shift - $labelLeft, $labelRight - 38 - $shift, $targetHalf + abs($shift));

        $viewboxX1 = 38 + $shift - $half;
        $viewboxX2 = 2 * $half;
    }

    $hasLegend = !empty($legend) && !empty($raisedA);
    if ($hasLegend){
        //count chars
        $maxRaised = max(array_map(static function($a, $b){ return donation_thermometer_strlen($a . $b); }, $raisedA, $legendA))
            + donation_thermometer_strlen($currency)
            + 3; // max legend width incl. space & ()
        if ($sep != ''){
            $maxRaised = $maxRaised + substr_count(number_format(max($raisedA),$decimals,$decsep,$sep), $sep);
        }
        if ($decimals > 0){
            $maxRaised = $maxRaised + ($decimals + 1); // incl. point
        }

        if($orientation == 'landscape'){
            $transformY = ($transformY - ($maxRaised*6.25)); // expand left
            $viewboxY = ($viewboxY + ($maxRaised*6.25)); // expand right
            $viewboxX2 = max($viewboxX2,count($legendA)*17); // expand down
        }
        else{
            $viewboxY = $viewboxY+(count($legendA)*$legendStep); // expand down
            $viewboxX2 = max($viewboxX2, $maxRaised*6.25); // expand right
        }

    }

    // shared geometry
    if ($orientation == 'landscape'){
        $borderPath = 'M 280 41.5 C 280 51.5 275.5 59.5 269.5 59.5 L 54.5 59.5 C 50.5 64 43.5 66.5 37.5 66.5 C 23.5 66.5 12.5 55.5 12.5 41.5 C 12.5 27.5 23.5 16.5 37.5 16.5 C 43.5 16.5 50.5 19.5 54.5 23.5 L 269.5 23.5 C 275.5 23.5 280 31.5 280 41.5';
    }
    else{
        $borderPath = 'M38 25.5 C 28 25.5, 20 30, '.$leftM.' '.$maxH.' L '.$leftM.' 251 C 15.5 255, 13 262, 13 268 C 13 282, 24 293, 38 293 C 52 293, 63 282, 63 268 C 63 262, 60 255, '.$rightM.' 251 L '.$rightM.' '.$maxH.' C '.$rightM.' 30, 48 25.5, 38 25.5';
    }

    // ticks run along X (backwards) in landscape and along Y in portrait
    $tickSegment = static function($pos, $from, $to) use ($orientation){
        return ($orientation == 'landscape') ? 'M '.$pos.' '.$from.' L '.$pos.' '.$to.' ' : 'M '.$from.' '.$pos.' L '.$to.' '.$pos.' ';
    };
    $tickDir = ($orientation == 'landscape') ? -1 : 1;
    $majorTicksD = '';
    $minorTicksD = '';
    for ($k = 0; $k <= 5; $k++){
        $majorTicksD .= $tickSegment($maxH + $tickDir*$tickStep*$k, $tickM, $majorTickL);
        if ($k < 5){
            $minorTicksD .= $tickSegment($maxH + $tickDir*$tickStep*($k + 0.5), $tickM, $minorTickL);
        }
    }
    $majorTicksD = trim($majorTicksD);
    $minorTicksD = trim($minorTicksD);

    // title/alt attribute
    if (strtolower(sanitize_text_field($thermProperties['title'])) == 'off'){
        $title = '';
    }
    elseif(!empty($thermProperties['title'])){
        $title = sanitize_text_field($thermProperties['title']);
    }
    else{
        $title = sprintf(__('Raised %1$s towards the %2$s target.', 'donation-thermometer'), $raisedValue, $targetValue);
    }

    // size properties
    $aspectRatio = $viewboxX2/$viewboxY; // width/height
    $workAround = 'n';
    
    $width = ($orientation == 'landscape') ? '501.5' : '200';
    $height = '';

    if (!empty($width_tp)){
        if (is_numeric(substr($width_tp,-1)) or substr($width_tp, -2) == 'px'){
            $width = preg_replace("/[^0-9.]/", "", $width_tp );
            $height = ($orientation == 'landscape') ? $width * $aspectRatio : $width / $aspectRatio;
        }
        elseif (substr($width_tp,-1) == '%'){
            $width = $width_tp;
            $height = intval($width_tp)/$aspectRatio.'%';
            $workAround = 'yesW';
        }
    }
    elseif (!empty($height_tp)){
        if (is_numeric(substr($height_tp,-1)) or substr($height_tp, -2) == 'px'){
            $height = preg_replace("/[^0-9.]/", "", $height_tp );
            $width = ($orientation == 'landscape') ? $height/$aspectRatio : $height * $aspectRatio;
        }
        elseif (substr($height_tp,-1) == '%'){
            $height = $height_tp;
            $workAround = 'yesH';
        }
    }

    /*
     *
     * start making the svg thermometer
     *
     */
    $align = donation_thermometer_normalize_align(
        $thermProperties['align'] ?? ''
    );

    $align_classes = array(
        'left'   => 'therm-align-left',
        'center' => 'therm-align-center',
        'right'  => 'therm-align-right',
    );

    $align_class = $align_classes[ $align ];

    $viewBox = ($orientation === 'landscape')
        ? $transformY . ' ' . $viewboxX1 . ' ' . $viewboxY . ' ' . $viewboxX2
        : $viewboxX1 . ' ' . $transformY . ' ' . $viewboxX2 . ' ' . $viewboxY;

    $svgSize  = '';
    $svgStyle = '';
    $canvas   = '';
    if ($workAround == 'yesW'){
        $wrapStyle = 'height:auto;width:' . $width . ';';
        $svgStyle  = 'display:block;width:100%;height:auto;';
    }
    elseif ($workAround == 'yesH'){
        if($orientation == 'landscape'){
            $wrapStyle = 'width: auto; height: ' . $height . ';';
            $svgStyle  = 'width: 100%;';
        }
        else{
            $wrapStyle = 'display:table;height:' . $height . ';position:relative;user-select:none;';
            $canvas    = '<canvas class="Icon-canvas" height="' . esc_attr( $viewboxY ) . '" width="' . esc_attr( $viewboxX2 ) . '" style="display:block;height:100% !important;visibility:hidden;"></canvas>';
            $svgStyle  = 'height:100%;left:0;position:absolute;top:0;width:100%;';
        }
    }
    else{
        $wrapStyle = 'display:table;height: ' . $height . 'px; width: ' . $width . 'px;';
        $svgSize   = ' x="0" y="0" width="' . esc_attr($width) . '" height="' . esc_attr($height) . '"';
        $svgStyle  = ($orientation == 'landscape') ? 'display: block;' : '';
    }

    echo '<div class="thermometer-container">';
    echo '<div class="thermometer-wrap ' . esc_attr( $align_class ) . '" style="' . esc_attr( $wrapStyle ) . '">';
    echo $canvas;
    echo '<svg xmlns="http://www.w3.org/2000/svg" version="2"' . $svgSize
        . ' viewBox="' . esc_attr( $viewBox ) . '" aria-label="' . esc_attr( $title ) . '" preserveAspectRatio="xMidYMid" class="thermometer_svg"'
        . ( $svgStyle !== '' ? ' style="' . esc_attr( $svgStyle ) . '"' : '' ) . '>';

    echo '<defs>'.$gradient;

    echo '<filter id="'.esc_attr($shadowID).'" x="-20%" y="-20%" height="150%" width="150%" filterUnits="objectBoundingBox">
        <feGaussianBlur in="SourceAlpha" stdDeviation="3" result="shadow"/> <!-- stdDeviation is how much to blur -->
        <feOffset dx="1.8" dy="1.8" result="offsetblur" in="shadow"/> <!-- how much to offset -->
        <feComponentTransfer result="shadow1" in="offsetblur">
            <feFuncA type="linear" slope="0.6"/> <!-- slope is the opacity of the shadow -->
        </feComponentTransfer>
        <feBlend in = "SourceGraphic" in2 = "shadow1" mode = "normal"/>
        </filter>';
    echo '<filter id="'.esc_attr($svg_id_prefix.'_blur').'">
          <!-- filter processes -->
          <feGaussianBlur in="SourceGraphic" stdDeviation="7.5"/><!-- stdDeviation is amount of blur -->
      </filter>
    <filter id="'.esc_attr($svg_id_prefix.'_blur2').'">
          <!-- filter processes -->
          <feGaussianBlur in="SourceGraphic" stdDeviation="2.2"/><!-- stdDeviation is amount of blur -->
      </filter>
  </defs>';
    echo '<desc>Created using the Donation Thermometer plugin https://wordpress.org/plugins/donation-thermometer/.</desc>';

    // outline overlay with shadow
    if ($shadow == 1){
        echo '<path d="'.esc_attr($borderPath).'" class="therm_border" filter="'.esc_attr($basicShadow).'" ></path>';
    }

    // target
    if ($showTarget == 1){
        if($orientation == 'landscape'){
            echo '<text x="'.esc_attr($targetAnchorPoint).'" y="'.esc_attr($subTargetMargin).'" class="therm_target" fill="'.esc_attr($targetColor).'" dominant-baseline="central" style="text-anchor:'.$targetAnchor.'!important">'.esc_html($tValue).'</text>';
        }
        else{
            echo '<text x="38" y="20" class="therm_target" fill="'.esc_attr($targetColor).'" dominant-baseline="auto" text-anchor="middle">'.esc_html($tValue).'</text>';
        }

    }

    // background fill with a transparent border
    $fill_style = !empty($optionsCSS['therm_fill_style']) ? safecss_filter_attr($optionsCSS['therm_fill_style']) : 'fill:transparent';
    echo '<path d="'.esc_attr($borderPath).'" style="'.esc_attr($fill_style).'; stroke-opacity: 0!important;"></path>';

    if ($shadow == 1){ // shadows only under fill
        echo '<path d="'.esc_attr($majorTicksD).'" class="therm_majorTick" filter="'.esc_attr($basicShadow).'"/>';
        echo '<path d="'.esc_attr($minorTicksD).'" class="therm_minorTick" filter="'.esc_attr($basicShadow).'"/>';
    }

    // fill
    $oldThermLevel = $minH;
    $newThermLevel = $minH;
    
    $maxLevel = ($swap == 0) ? $minH - (($minH - $maxH) * ($raisedTotal/$targetTotal)) : $minH - (($minH - $maxH) * ($targetTotal/$raisedTotal));

    $i = 0;
    $raisedN = count($raisedA) - 1;

    if($orientation == 'landscape'){
        if($shadow == 1 && $raisedTotal <= $targetTotal){ // extra shadow for fill
            echo '<path d="M '.esc_attr($maxLevel).' 59.5 L 54.5 59.5 C 50.5 64 43.5 66.5 37.5 66.5 C 23.5 66.5 12.5 55.5 12.5 41.5 C 12.5 27.5 23.5 16.5 37.5 16.5 C 43.5 16.5 50.5 19.5 54.5 23.5 L '.esc_attr($maxLevel).' 23.5 L '.esc_attr($maxLevel).' 59.5" style="stroke-width: 0;" filter="'.esc_attr($basicShadow).'"></path>';
        }
        elseif($shadow == 1 && $raisedTotal > $targetTotal){ // extra shadow for fill
            echo '<path d="'.esc_attr($borderPath).'" style="stroke-width: 0;"  filter="'.esc_attr($basicShadow).'"></path>';
        }
        foreach($raisedA as $r){
            if ($i == 0) {
                $newThermLevel = ($raisedTotal > $targetTotal) ? $minH - (($minH - $maxH) * ($r/$raisedTotal)) : $minH - (($minH - $maxH) * ($r/$targetTotal));
                if($raisedTotal > $targetTotal){
                    echo '<path d="'.esc_attr($borderPath).'" style="stroke-width: 0;" fill="url(#'.esc_attr($gradID).')"/>';
                }
                else{
                    echo '<path d="M '.esc_attr($newThermLevel).' '.esc_attr($rightM).' L 54.5 '.esc_attr($rightM).' C 50.5 64 43.5 66.5 37.5 66.5 C 23.5 66.5 12.5 55.5 12.5 41.5 C 12.5 27.5 23.5 16.5 37.5 16.5 C 43.5 16.5 50.5 19.5 54.5 '.esc_attr($leftM).' L '.esc_attr($newThermLevel).' '.esc_attr($leftM).' L '.esc_attr($newThermLevel).' '.esc_attr($rightM).'" style="stroke-width: 0;" fill="url(#'.esc_attr($gradID).')"/>';
                }

                if ($i == $raisedN && $raisedTotal <= $targetTotal){
                    echo '<path d="M '.esc_attr($newThermLevel).' '.esc_attr($leftM).' L '.esc_attr($newThermLevel).' '.esc_attr($rightM).'" class="therm_raisedLevel" />';
                }
            }
            else{
                ##$fill = ($i > count($colorListA)-1) ? esc_attr($thermProperties['fill']) : trim($colorListA[$i]); // if not enough colours in list -> transparent
                $fill = ($i > count($colorListA)-1) ? 'url(#'.$gradID.')' : trim($colorListA[$i]); // if not enough colours in list -> transparent
                $newThermLevel = ($raisedTotal > $targetTotal) ? $oldThermLevel - (($minH - $maxH) * ($r/$raisedTotal)) : $oldThermLevel - (($minH - $maxH) * ($r/$targetTotal));
                if ($raisedTotal > $targetTotal && $i == $raisedN){
                    echo '<path d="M '.esc_attr($maxH).' '.esc_attr($rightM).' L '.esc_attr($oldThermLevel).' '.esc_attr($rightM).' L '.esc_attr($oldThermLevel).' '.esc_attr($leftM).' '.esc_attr($maxH).' '.esc_attr($leftM).' C 275.5 23.5 280 31.5 280 41.5 C 280 51.5 275.5 59.5 269.5 59.5" fill="'.esc_attr($fill).'" style="stroke-width: 0;"/>';
                }
                else{
                    echo '<rect x="'.esc_attr($oldThermLevel).'" y="'.esc_attr($leftM).'" width="'.esc_attr($newThermLevel-$oldThermLevel).'" height="'.esc_attr($rightM-$leftM).'" fill="'.esc_attr($fill).'" style="stroke-width: 0;"/>';
                }

                echo '<path d="M '.esc_attr($oldThermLevel).' '.esc_attr($leftM).' L '.esc_attr($oldThermLevel).' '.esc_attr($rightM).'" class="therm_subRaisedLevel"/>';

                if ($i == $raisedN && $raisedTotal <= $targetTotal){
                    echo '<path d="M '.esc_attr($newThermLevel).' '.esc_attr($leftM).' L '.esc_attr($newThermLevel).' '.esc_attr($rightM).'" class="therm_subRaisedLevel"/>';
                }
            }
            $i++;
            $oldThermLevel = $newThermLevel;
        }
    }

    else{ /// portrait
        if($shadow == 1 && $raisedTotal <= $targetTotal){ // extra shadow for fill
            echo '<path d="M'.esc_attr($leftM.' '.$maxLevel).' L '.esc_attr($leftM).' 251 C 15.5 255, 13 262, 13 268 C 13 282, 24 293, 38 293 C 52 293, 63 282, 63 268 C 63 262, 60 255, '.esc_attr($rightM).' 251 L '.esc_attr($rightM).' '.esc_attr($maxLevel).' L '.esc_attr($leftM).' '.esc_attr($maxLevel).'" style="stroke-width: 0;" filter="'.esc_attr($basicShadow).'"></path>';
        }
        elseif($shadow == 1 && $raisedTotal > $targetTotal){ // extra shadow for fill
            echo '<path d="M'.esc_attr($leftM).' '.esc_attr($maxH).' L '.esc_attr($leftM).' 251 C 15.5 255, 13 262, 13 268 C 13 282, 24 293, 38 293 C 52 293, 63 282, 63 268 C 63 262, 60 255, '.esc_attr($rightM).' 251 L '.esc_attr($rightM).' '.esc_attr($maxH).' C '.esc_attr($rightM).' 30, 48 25.5, 38 25.5 C 28 25.5, 20 30, '.esc_attr($leftM).' '.esc_attr($maxH).'" style="stroke-width: 0;" filter="'.esc_attr($basicShadow).'"/>';
        }

        foreach($raisedA as $r){
            if ($i == 0) {
                $newThermLevel = ($raisedTotal > $targetTotal) ? $minH - (($minH - $maxH) * ($r/$raisedTotal)) : $minH - (($minH - $maxH) * ($r/$targetTotal));
                if($raisedTotal > $targetTotal){
                    echo '<path d="M'.esc_attr($leftM).' '.esc_attr($newThermLevel).' L '.esc_attr($leftM).' 251 C 15.5 255, 13 262, 13 268 C 13 282, 24 293, 38 293 C 52 293, 63 282, 63 268 C 63 262, 60 255, '.esc_attr($rightM).' 251 L '.esc_attr($rightM).' '.esc_attr($newThermLevel).' C '.esc_attr($rightM).' 30, 48 25.5, 38 25.5 C 28 25.5, 20 30, '.esc_attr($leftM).' '.esc_attr($newThermLevel).'" style="stroke-width: 0;" fill="url(#'.esc_attr($gradID).')"/>';
                }
                else{
                    echo '<path d="M'.esc_attr($leftM).' '.esc_attr($newThermLevel).' L '.esc_attr($leftM).' 251 C 15.5 255, 13 262, 13 268 C 13 282, 24 293, 38 293 C 52 293, 63 282, 63  268 C 63 262, 60 255, '.esc_attr($rightM).' 251 L '.esc_attr($rightM).' '.esc_attr($newThermLevel).' L '.esc_attr($leftM).' '.esc_attr($newThermLevel).'" style="stroke-width: 0;" fill="url(#'.esc_attr($gradID).')"/>';
                }

                if ($i == $raisedN && $raisedTotal <= $targetTotal){
                    echo '<path d="M'.esc_attr($leftM).' '.esc_attr($newThermLevel).' L '.esc_attr($rightM).' '.esc_attr($newThermLevel).'" class="therm_raisedLevel" />';
                }
            }
            else{
                ##$fill = ($i > count($colorListA)-1) ? esc_attr($thermProperties['fill']) : trim($colorListA[$i]); // if not enough colours in list -> transparent
                $fill = ($i > count($colorListA)-1) ? 'url(#'.$gradID.')' : trim($colorListA[$i]); // if not enough colours in list -> transparent
                $newThermLevel = ($raisedTotal > $targetTotal) ? $oldThermLevel - (($minH - $maxH) * ($r/$raisedTotal)) : $oldThermLevel - (($minH - $maxH) * ($r/$targetTotal));
                if ($raisedTotal > $targetTotal && $i == $raisedN){
                    echo '<path d="M '.esc_attr($leftM).' '.esc_attr($newThermLevel).' L '.esc_attr($leftM).' '.esc_attr($oldThermLevel).' L '.esc_attr($rightM).' '.esc_attr($oldThermLevel).' L '.esc_attr($rightM).' '.esc_attr($newThermLevel).' C '.esc_attr($rightM).' 30, 48 25.5, 38 25.5 C 28 25.5, 20 30, '.esc_attr($leftM).' '.esc_attr($newThermLevel).'" fill="'.esc_attr($fill).'" style="stroke-width: 0;" />';
                }
                else{
                    echo '<rect x="'.esc_attr($leftM).'" y="'.esc_attr($newThermLevel).'" width="'.esc_attr($rightM-$leftM).'" height="'.esc_attr($oldThermLevel-$newThermLevel).'" fill="'.esc_attr($fill).'" style="stroke-width: 0;"/>';
                }


                echo '<path d="M '.esc_attr($leftM).' '.esc_attr($oldThermLevel).' L '.esc_attr($rightM).' '.esc_attr($oldThermLevel).'" class="therm_subRaisedLevel"/>';

                if ($i == $raisedN && $raisedTotal <= $targetTotal){
                    echo '<path d="M '.esc_attr($leftM).' '.esc_attr($newThermLevel).' L '.esc_attr($rightM).' '.esc_attr($newThermLevel).'" class="therm_subRaisedLevel"/>';
                }
            }
            $i++;
            $oldThermLevel = $newThermLevel;
        }
    }

    // raised value & ticks
    if ( !empty($raisedValue) && $showRaised == 1 ){
        $rValue = ($swap == 0) ? $raisedValue : $targetValue;
        $rValueLevel = ($swap == 0) ? $newThermLevel : $minH - (($minH - $maxH) * ($targetTotal/$raisedTotal));
        if($orientation == 'landscape'){
            if ( $tickM == $rightM ){
                echo '<path d="M '.esc_attr($rValueLevel).' '.esc_attr($markerMargin).', '.esc_attr($rValueLevel-$markerSize).' '.esc_attr($markerMargin+$markerSize).', '.esc_attr($rValueLevel+$markerSize).' '.esc_attr($markerMargin+$markerSize).' Z" class="therm_arrow"/>';
            }
            else{
                echo '<path d="M '.esc_attr($rValueLevel).' '.esc_attr($markerMargin).', '.esc_attr($rValueLevel+$markerSize).' '.esc_attr($markerMargin-$markerSize).', '.esc_attr($rValueLevel-$markerSize).' '.esc_attr($markerMargin-$markerSize).' Z" class="therm_arrow" />';
            }

            echo '<text x="'.esc_attr($rValueLevel).'" y="'.esc_attr($raisedMargin).'" class="therm_raised" text-anchor="middle" dominant-baseline="central" fill="'.esc_attr($raisedColor).'">'.esc_html($rValue).'</text>';
            if ($swap == 1){
                echo '<path d="M'.esc_attr($rValueLevel).' '.esc_attr($leftM).' L '.esc_attr($rValueLevel).' '.esc_attr($rightM).'" class="therm_subTargetLevel"/>';
            }
        }

        else{
            if ( $tickM == $rightM ){
                echo '<path d="M '.esc_attr($markerMargin).' '.esc_attr($rValueLevel).', '.esc_attr($markerMargin+$markerSize).' '.esc_attr($rValueLevel-$markerSize).', '.esc_attr($markerMargin+$markerSize).' '.esc_attr($rValueLevel+$markerSize).' Z" class="therm_arrow"/>';
            }
            else{
                echo '<path d="M '.esc_attr($markerMargin).' '.esc_attr($rValueLevel).', '.esc_attr($markerMargin-$markerSize).' '.esc_attr($rValueLevel+$markerSize).', '.esc_attr($markerMargin-$markerSize).' '.esc_attr($rValueLevel-$markerSize).' Z" class="therm_arrow" />';
            }
            echo '<text x="'.esc_attr($raisedMargin).'" y="'.esc_attr($rValueLevel).'" class="therm_raised" text-anchor="'.esc_attr($raisedAnchor).'" dominant-baseline="central" fill="'.esc_attr($raisedColor).'">'.esc_html($rValue).'</text>';
            if ($swap == 1){
                echo '<path d="M'.esc_attr($leftM).' '.esc_attr($rValueLevel).' L '.esc_attr($rightM).' '.esc_attr($rValueLevel).'" class="therm_subTargetLevel"/>';
            }
        }
    }

    // multiple subtargets
    if( count($targetA) > 1 ){ // only if multiple targets
        foreach( array_slice($targetA,0,-1) as $t ){ // and skip the last target total
            $targetLevel = $minH - (($minH - $maxH) * ($t/$targetTotal));
            if ($orientation == 'portrait'){ // horizontal markers
                echo '<path d="M'.esc_attr($leftM).' '.esc_attr($targetLevel).' L '.esc_attr($rightM).' '.esc_attr($targetLevel).'" class="therm_subTargetLevel"/>';
            }
            else{
                echo '<path d="M'.esc_attr($targetLevel).' '.esc_attr($leftM).' L '.esc_attr($targetLevel).' '.esc_attr($rightM).'" class="therm_subTargetLevel"/>';
            }
            if ($raisedTotal <= $t*0.9 or $raisedTotal >= $t*1.1 or $showRaised == 0){ // within 10% but only when not reached the subtotal
                if ($showSubTargets == 1){
                    $t_formatted = esc_html($formatValue($t));
                    if ($orientation == 'portrait'){
                        if ( $tickM == $rightM ){
                            echo '<path d="M '.esc_attr($markerMargin).' '.esc_attr($targetLevel).', '.esc_attr($markerMargin+$markerSize).' '.esc_attr($targetLevel-$markerSize).', '.esc_attr($markerMargin+$markerSize).' '.esc_attr($targetLevel+$markerSize).' Z" class="therm_subTargetArrow"/>';
                        }
                        else{
                            echo '<path d="M '.esc_attr($markerMargin).' '.esc_attr($targetLevel).', '.esc_attr($markerMargin-$markerSize).' '.esc_attr($targetLevel+$markerSize).', '.esc_attr($markerMargin-$markerSize).' '.esc_attr($targetLevel-$markerSize).' Z" class="therm_subTargetArrow" />';
                        }

                        echo '<text x="'.esc_attr($raisedMargin).'" y="'.esc_attr($targetLevel).'" fill="'.esc_attr($subTargetColor).'" class="therm_subTarget" text-anchor="'.esc_attr($raisedAnchor).'" dominant-baseline="central">'.$t_formatted.'</text>';
                    }
                    elseif($orientation == 'landscape'){
                        if ( $tickM == $rightM ){
                            echo '<path d="M '.esc_attr($targetLevel).' '.esc_attr($subMarkerMargin).', '.esc_attr($targetLevel+$markerSize).' '.esc_attr($subMarkerMargin-$markerSize).', '.esc_attr($targetLevel-$markerSize).' '.esc_attr($subMarkerMargin-$markerSize).' Z" class="therm_subTargetArrow"/>';
                        }
                        else{
                            echo '<path d="M '.esc_attr($targetLevel).' '.esc_attr($subMarkerMargin).', '.esc_attr($targetLevel-$markerSize).' '.esc_attr($subMarkerMargin+$markerSize).', '.esc_attr($targetLevel+$markerSize).' '.esc_attr($subMarkerMargin+$markerSize).' Z" class="therm_subTargetArrow" />';
                        }

                        echo '<text x="'.esc_attr($targetLevel).'" y="'.esc_attr($subTargetMargin).'" fill="'.esc_attr($subTargetColor).'" class="therm_subTarget" text-anchor="middle" dominant-baseline="central">'.$t_formatted.'</text>';
                    }
                }
            }
        }
    }


    echo '<path d="'.esc_attr($majorTicksD).'" class="therm_majorTick"/>';
    echo '<path d="'.esc_attr($minorTicksD).'" class="therm_minorTick"/>';

    // outline overlay	// title needs to be a child element to display as tooltip
    echo '<path d="'.esc_attr($borderPath).'" class="therm_border"><title>'.esc_html($title).'</title></path>';

    // percentage
    if ((int) $thermProperties['showPercent'] === 1){
        $percentLen = donation_thermometer_strlen($raisedPercent);
        $fontS_percent = ($percentLen < 3) ? 17 : (($percentLen < 4) ? 15 : (($percentLen < 6) ? 12 : 10));

        if($orientation == 'landscape'){
            echo '<text x="37.5" y="41.5" class="therm_percent" style="text-anchor:middle;font-size: '.$fontS_percent.'px" dominant-baseline="central"  fill="'.esc_attr($percentageColor).'">'.esc_html($raisedPercent).'%</text>';
        }
        else{
            echo '<text x="38" y="274" class="therm_percent" style="font-size: '.$fontS_percent.'px" text-anchor="middle" fill="'.esc_attr($percentageColor).'">'.esc_html($raisedPercent).'%</text>';
        }
    }

    // legend
    if($hasLegend){
        $legendAr = array_reverse($legendA);
        $raisedAr = array_reverse($raisedA);
        $i = count($raisedAr) - 1; // for color
        $i2 = count($legendAr) - 1;
        $j = 0;

        if($orientation == 'landscape'){
            $legendLevel = 10;
            echo '<text class="therm_legend" x="'.($legendLevel-10).'" y="'.max(0,(41.5-((($legendStep+6)*count($legendAr))/2))).'" text-anchor="end" dominant-baseline="central">';
        }
        else{
            $legendLevel = 295;
            echo '<text class="therm_legend" x="'.($viewboxX1+4).'" y="'.$legendLevel.'" dominant-baseline="baseline" text-anchor="start">';
        }
        foreach($raisedAr as $r){
            if($i > $i2){
                $i--;
                continue;
            }
            $legendColor = (array_key_exists($i, $colorListA)) ? trim($colorListA[$i]) : 'black';
            if($orientation == 'landscape'){
                echo '<tspan x="'.esc_attr($legendLevel-10).'" dy="'.esc_attr($legendStep).'" fill="'.esc_attr($legendColor).'" text-anchor="end" alignment-baseline="central">'.esc_html($legendAr[$j]);
            }
            else{
                echo '<tspan x="'.esc_attr($viewboxX1+4).'" dy="'.esc_attr($legendStep).'" fill="'.esc_attr($legendColor).'" text-anchor="start" alignment-baseline="central">'.esc_html($legendAr[$j]);
            }
            echo esc_html(' ('.$formatValue($r).')').'</tspan>';

            $i--;
            $j++;
        }
        echo '</text>';
    }

    echo '</svg></div></div>';

    return ob_get_clean();
}
